project:
  type: website
  output-dir: docs
  resources:
    - assets/schools.geojson

# website:
  # title: "DSAN Alumni Outcomes"
  # navbar:
  #   search: false
  #   left:
  #     - href: index.qmd
  #       text: Home

format:
  html:
    theme: cosmo
    css: styles.css