project:
  type: website
  output-dir: docs
  resources:
    - assets/geocoded.geojson
    - assets/caslon.otf

# website:
  # title: "DSAN Alumni Outcomes"
  # navbar:
  #   search: false
  #   left:
  #     - href: index.qmd
  #       text: Home

format:
  html:
    theme: flatly
    css: styles.css
    mainfont: "Caslon, serif"